# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: compile

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            NAME: ubuntu
            OUT_FILE_NAME: ubuntu.zip
            POST_BUILD_CMD: cd dist/ && zip ubuntu ubuntu
            COMMAND: pyinstaller --distpath dist/ubuntu "main.spec"

          - os: macos-latest
            NAME: macos
            OUT_FILE_NAME: macos.zip
            POST_BUILD_CMD: cd dist/ && zip macos macos
            COMMAND: pyinstaller --distpath dist/macos "main.spec"

          - os: windows-latest
            NAME: windows
            OUT_FILE_NAME: windows.zip
            POST_BUILD_CMD: cd dist/ && tar.exe -c -f windows.zip windows
            COMMAND: pyinstaller --distpath dist/windows "main.spec"

          #   ASSET_MIME: application/vnd.microsoft.portable-executable

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies for ${{ matrix.config.os }}
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Compile for ${{ matrix.config.os }}
        run: ${{ matrix.config.COMMAND }}

      - name: Post-Build for ${{ matrix.config.os }}
        if: ${{ matrix.config.POST_BUILD_CMD != '' }}
        run: ${{ matrix.config.POST_BUILD_CMD }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: './dist/${{matrix.config.OUT_FILE_NAME}}'

      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config.NAME}}
          path: './dist/${{matrix.config.NAME}}/'
