# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Compile

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: DEV
        required: true
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            NAME: ubuntu
            OUT_FILE_NAME: ubuntu.zip
            POST_BUILD_CMD: cd dist/ && zip ubuntu ubuntu
            COMMAND: pyinstaller --distpath dist/ubuntu "main.spec"

          # - os: macos-latest
          #   NAME: macos
          #   OUT_FILE_NAME: macos.zip
          #   POST_BUILD_CMD: cd dist/ && zip macos macos
          #   COMMAND: pyinstaller --distpath dist/macos "main.spec"

          - os: windows-latest
            NAME: windows
            OUT_FILE_NAME: windows/h5viewer.exe #windows.zip
            # POST_BUILD_CMD: cd dist/ && tar.exe -c -f windows.zip windows
            COMMAND: pyinstaller --distpath dist/windows "main.spec"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies for ${{ matrix.config.os }}
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Compile for ${{ matrix.config.os }}
        run: ${{ matrix.config.COMMAND }}
        env:
          PYINSTALLER: True

      - name: Post-Build for ${{ matrix.config.os }}
        if: ${{ matrix.config.POST_BUILD_CMD != '' }}
        run: ${{ matrix.config.POST_BUILD_CMD }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config.NAME}}
          path: './dist/${{matrix.config.NAME}}/'

      - name: Release
        if: startsWith(github.ref, 'refs/heads/release/')
        uses: softprops/action-gh-release@v1
        with:
          files: './dist/${{matrix.config.OUT_FILE_NAME}}'
